PJT/project_06/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies', include('movies.urls')),
]

PJT/project_06/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name='detail'),
]

PJT/project_06/movies/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    title_en = models.CharField(max_length=20)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=20)
    watch_grade = models.CharField(max_length=20)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()
    
    class Meta:
        ordering = ('-pk',)

    def get_absolute_url(self):
        return reverse("movies:detail", kwargs={'movies_pk': self.pk})

class Review(models.Model):
    content = models.CharField(max_length=100)
    score = models.IntegerField()
    movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-pk',)

PJT/project_06/movies/forms.py
from django import forms
from .models import Movie, Review

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

PJT/project_06/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Review
from .forms import MovieForm, ReviewForm

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {'movies': movies}
    return render(request, 'movies/index.html', context)


def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:index')
    else:
        form = MovieForm()
    context = {'form': form,}
    return render(request, 'movies/create.html', context)

def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    context = {'movie': movie,}
    return render(request, 'movies/detail.html', context)

PJT/project_06/crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>PROJECT_06</title>
</head>
<body>
  {% block content %}
  {% endblock %}
</body>
</html>

PJT/project_06/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<h1>CREATE</h1>
<form action="" method="POST">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="submit">
</form>
<a href="{% url 'movies:index' %}">[BACK]</a>
{% endblock  %}

PJT/project_06/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>DETAIL</h1>
<h2>{{ movie.pk }}번째 영화</h2>
<p>제목 : {{ movie.title }}</p>
{% endblock %}

PJT/project_06/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<h1>MOVIES</h1>
<a href="{% url 'movies:create' %}">[NEW]</a>
<hr>
{% for movie in movies %}
<p>영화 번호: {{ movie.pk }}</p>
<p>title: {{ movie.title }}</p>
<a href="{% url 'movies:detail' movie.pk %}">[DETAIL]</a>
<hr>
{% endfor %}
{% endblock %}