03_django/02_django_crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), # NEW(GET) + CREATE(POST)
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'), # EDIT(GET) + UPDATE(POST)
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'), # DETAIL(GET) + CREATE(POST)
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete') # DETAIL(GET) + DELETE(POST)
]

03_django/02_django_crud/articles/models.py
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import Thumbnail
from django.urls import reverse
from django.db import models

def articles_image_path(instance, filename):
    return f'articles/{instance.pk}/images/{filename}'

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    # image = models.ImageField(blank=True)
    # image_thumbnail = ImageSpecField(
    #     source='image', # 원본 ImageField 이름
    #     processors=[Thumbnail(200,300)],
    #     format='JPEG',
    #     options={'quality': 90},
    # )
    image = ProcessedImageField(
        # ProcessedImageField 에 인자로 들어가 있는 값들은 migrations 이후에
        # 추가되거나 수정되더라도 makemigrations 를 하지 않아도 된다.
        processors=[Thumbnail(200, 300)], # 처리할 작업 목록
        format='JPEG', # 저장 포맷
        options={'quality': 90}, # 추가 옵션들
        upload_to='articles/images', # 저장 위치 (MEDIA_ROOT/article/images)
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return f'/articles/{self.pk}/'
        # return reverse('articles:detail', args=[self.pk]) # /articles/10/
        return reverse('articles:detail', kwargs={'article_pk': self.pk}) # /articles/10/
        # 주의사항
        # reverse 함수에 args 랑 kwargs 를 동시에 인자로 보낼 수 없다.


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        # return self.
        return f'<Article({self.article_id}): Comment({self.pk})-{self.content}'

    

03_django/02_django_crud/articles/views.py
from IPython import embed
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from .models import Article, Comment

# Create your views here.
def index(request):
    articles = Article.objects.order_by('-pk') # DB 가 변경
    # articles = Article.objects.all()[::-1] # python 이 변경
    
    context = {'articles': articles,}
    return render(request, 'articles/index.html', context)


def create(request):
    # CREATE
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        article = Article(title=title, content=content, image=image)
        article.save()
        return redirect(article) # detail
    # NEW
    else:
        return render(request, 'articles/create.html')


def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comments = article.comment_set.all()
    context = {'article': article, 'comments': comments,}
    return render(request, 'articles/detail.html', context)


def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect(article)


def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.image = request.FILES.get('image')
        article.save()
        return redirect(article)
    else:
        context = {'article': article,}
        return render(request, 'articles/update.html', context)


def comments_create(request, article_pk):
    # 댓글을 달 게시글
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        # form 에서 넘어온 댓글 정보
        content = request.POST.get('content')
        # 댓글 생성 및 저장
        comment = Comment(article=article, content=content)
        comment.save()
        return redirect(article)
        # return redirect('articles:detail' article.pk)
        # return redirect('articles:detail' article_pk)
    else:
        return redirect(article)


def comments_delete(request, article_pk, comment_pk):
    # article = Article.objects.get(pk=article_pk)
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
    # return redirect(article)
    return redirect('articles:detail', article_pk)

03_django/02_django_crud/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <img src="{% static 'images/wolf_2.jpg' %}" alt="assets_img">
  <h1 class="text-center">CREATE</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title" required><br>
    <label for="content">CONTENT</label>
    <textarea name="content" id="content" cols="30" rows="5"></textarea><br>
    <label for="image">IMAGE</label>
    <input type="file" name="image" id="image" accept="image/*">
    <input type="submit" value="submit">
  </form>
{% endblock %}

03_django/02_django_crud/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <img src="{{ article.image_thumbnail.url }}" alt="썸네일">




  <h1 class="text-center">DETAIL</h1>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% else %}
    <img src="{% static 'articles/images/no_img.jpg' %}" alt="no_img">
  {% endif %}
  <h2>{{ article.pk }} 번째 글</h2>
  <hr>
  <p>제목: {{ article.title }}</p>
  <p>내용: {{ article.content }}</p>
  <p>작성 시각: {{ article.created_at }}</p>
  <p>수정 시각: {{ article.updated_at }}</p>
  <hr>
  <!-- 댓글 출력 -->
  <p><b>{{ comments|length }}개의 댓글</b></p>
  {% for comment in comments %}
    <li>
      {{ comment.content }}
      <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <input type="submit" value="DELETE">
      </form>
    </li>
  {% empty %}
    <p><b>댓글이 없어요..</b></p>
  {% endfor %}
  <hr>
  <!-- 댓글 작성 form -->
  <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="content">COMMENT</label>
    <input type="text" name="content" id="content">
    <input type="submit" value="submit">
  </form>
  <hr>
  <a href="{% url 'articles:update' article.pk %}">[UPDATE]</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('진짜 지울거야??')">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock %}

03_django/02_django_crud/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1 class='text-center'>EDIT</h1>
  <form action="/articles/{{ article.pk }}/update/" method='POST'>
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title" value="{{ article.title }}"><br>
    <label for="content">CONTENT</label>
    <textarea name="content" id="content" cols="30" rows="5">{{ article.content }}</textarea><br>
    <input type="submit" value="submit">
  </form>
  <a href="/articles/{{ article.pk }}/">[back]</a>
{% endblock %}

03_django/02_django_crud/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <img src="{% static 'articles/images/wolf.jpg' %}" alt="sample_img">
  <h1 class="text-center">Articles</h1>
  <a href="{% url 'articles:create' %}">[NEW]</a>
  <hr>
  {% for article in articles %}
    <p>글 번호: {{ article.pk }}</p>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <a href="{{ article.get_absolute_url }}">[DETAIL]</a>
    <hr>
  {% endfor %}
{% endblock %}

03_django/02_django_crud/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1 class='text-center'>NEW</h1>
  <form action="/articles/create/" method='POST'>
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title"><br>
    <label for="content">CONTENT</label>
    <textarea name="content" id="content" cols="30" rows="5"></textarea><br>
    <input type="submit" value="submit">
  </form>
{% endblock %}

03_django/02_django_crud/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1 class="text-center">UPDATE</h1>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="sample">
  {% else %}
    <img src="{% static 'articles/images/no_img.jpg' %}" alt="no_img">
  {% endif %}
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title" value="{{ article.title }}"><br>
    <label for="content">CONTENT</label>
    <textarea name="content" id="content" cols="30" rows="5">{{ article.content }}</textarea><br>
    <label for="image">IMAGE</label>
    <input type="file" name="image" id="image" accept="image/*"><br>
    <input type="submit" value="submit">
  </form>
  <a href="{{ article.get_absolute_url }}">[back]</a>
{% endblock %}